"""empty message

Revision ID: 34f72a8dfcb
Revises: None
Create Date: 2016-02-18 19:08:41.122390

"""

# revision identifiers, used by Alembic.
revision = '34f72a8dfcb'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('tiny_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_url_url'), 'url', ['url'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_url'), table_name='url')
    op.drop_table('url')
    ### end Alembic commands ###
